---

  - name: Installing and Launching Filebeat and Metricbeat
    hosts: webservers
    become: True
    tasks:

    - name: Download .deb Filebeat File
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

    - name: Download .deb Metricbeat File
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

    - name: Install .deb Filebeat File
      command: dpkg -i filebeat-7.4.0-amd64.deb

    - name: Install .deb Metricbeat File
      command: dpkg -i metricbeat-7.6.1-amd64.deb

    - name: Copy Filebeat config to WebVMs
      copy:
        src: /etc/ansible/files/filebeat-config.yml
        dest: /etc/filebeat/filebeat.yml

    - name: Copy Metricbeat config to WebVMs
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: Enable Filebeat
      command: filebeat modules enable system

    - name: Metricbeat Enable Docker
      command: metricbeat modules enable docker

    - name: Filebeat Setup
      command: filebeat setup

    - name: Metricbeat Setup
      command: metricbeat setup

    - name: Start Filebeat
      command: service filebeat start

    - name: Start Metricbeat
      command: service metricbeat start
